-- Sustituir {{ID_ENTIDAD}} por un ID GoldenRecord de 9 dígitos validado.
SELECT
    DQ.ID,
    DQ.ID_SISTEMA,
    DQ.ID_TIPO_ENTIDAD,
    DQ.ID_EXTERNO,
    DQ.FECHA_PETICION,
    DQ.CODIGO_ERROR,
    DQ."descripcion_error"
FROM LGC_GOLDENRECORD.v_hist_error_dqdg_pendientes DQ
INNER JOIN LGC_GOLDENRECORD.V_CORRELACIONES C
        ON C.ID_SISTEMA = DQ.ID_SISTEMA
       AND C.ID_EXTERNO = DQ.ID_EXTERNO
       AND C.ID_TIPO_ENTIDAD = DQ.ID_TIPO_ENTIDAD
WHERE C.ID_TIPO_ENTIDAD = 2
  AND C.ID_ENTIDAD = {{ID_ENTIDAD}};
